config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'

  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  validates :username, presence: true, length: { minimum: 3, maximum: 15}, uniqueness: { case_sensitive: false }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You need to be logged in to do that."
      redirect_to login_path
    end

  end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController

  before_action :require_user, only: [:index]

  def index
    @messages = Message.all.last(20)
    @message = Message.new
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", {
        mod_message:message_render(message)
      }
    end
  end


  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', :locals => {message: message})
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :logged_in_redirect, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:alert] = "You have been logged in."
      redirect_to root_path
    else 
      flash.now[:error] = "You could not be logged in."
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been logged out."
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in."
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.username.downcase
    if @user.save
      flash[:notice] = "You have successfully created an account and logged in."
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end


  def user_params
    params.require(:user).permit(:username, :password)
  end

  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular coffee icon orange"></i>
  Say something
</h4>

<div class="ui two column grid">

  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: { class: "ui reply form", role: "form"}, url: message_path, remote: true) do  |f|%>
         <div class="field">
            <div class="ui fluid icon input">
                <%= f.text_field :body, id: "message-input"%>
              <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
            </div>
          </div>
        <%end%> 
      </div>
    </div>
  </div>
    <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">Item 1</a>
          <a class="item">Item 2</a>
          <a class="item">Item 3</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|%>
  <div class="ui message transition <%=name%>">
    <i class="close icon"></i>
    <div class="header">
      <%=msg%>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui tiny menu inverted">
  <div class="ui container">
 <%= link_to 'Chatroom', root_path, class: "item" %>
  <a class="item">
    Messages
  </a>
  <div class="right menu">
    <div class="ui dropdown item">
      Account <i class="dropdown icon"></i>
      <div class="menu">
        <% if logged_in?%>
          <%= link_to "Log out", logout_path, method: :delete, class: "item" %>
        <% else %>
          <%= link_to 'Log in', login_path, class: "item" %>
          <%= link_to 'Sign up', signup_path, class: "item" %>
        <% end %>
       
      </div>
    </div>
    <% if !logged_in? %>
      <div class="item">
        <div class="ui primary button">Sign Up</div>
      </div>
    <% end %>
  </div>
</div> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsChat</title>
    <%= favicon_link_tag%>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render "layouts/navigation"%>
  <%= render "layouts/messages"%>
  
  <div class="ui container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
      <div class="content">
        <div class="summary">
          <em>><%=message.user.username %></em>: <%=message.body%>
        </div>
      <div>
      </div>
    </div>
  </div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert">
    <p>The following errors prevented the <%= obj.class.name.downcase %> from being saved</p>
    <h4 class="alert-heading"> Errors</h4>
    <% obj.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", obj: @user%>

<div class="ui two column centered grid">
  <%= form_with(model: @user, local: true, class: "ui form column") do |f|%>
  <div class="field">
    <%= f.label :username %> <br/>
    <%= f.text_field :username, class: "form-control"%>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password%>
  </div>

  <div class="field">
    <%= f.submit(@user.new_record? ? "Sign Up" : "Update account", class: "ui primary button")%>
  </div>

  <% end %>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render "form" %>